language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]]; then
    travis_terminate 0
  fi
before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P bintray-drogeek-d35-mvn
    deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
  - gh-pages
  - master
env:
  matrix:
    secure: yKd25JjAoZbEYoNQpkO5GBrlG2T9D+gU3H4VctEBL4W0yjKFVnrnxmwvjTymb6WUs+vDSNgwxqKQqJ0bDviPbpp0+yEgfIO2gvc8lBrOubnFuE1qSBrHdKqlPuuGdd6s/7jUM1OX94QLx6qopQJd9YU6ohafSZh2cpghHa0UzaKR1yktG2Ehe0zMxdbe66l7Kt6nHH5Qum6oC2UQZQbKCSKL3C/Dh/ZTzqAO6cN6OB9n263JxrVtc/CynqcqC3CMKNzWaJc3jJXsn03pys9IZgDeHNNYc6Qw0RmzrL0KhWmCZY58ao5AAWjDTLx9/2ZBFpLOnYmqJ4XiyvS4Bh0KjULTW/SF5WadAIfjK+UY+Nq5EMTJSqf/TeAZtXzkEjvle6Ab3VD5ruo2bHyPQzwiaggBcfr6jUF3mk+fTeOBvgMWq4zh01Wj5fo9tdXZk3otuTBWWrAF/CYPgBSleV4Xp2IdGupRPxLYv+bTBBZx9uhyz24MKlwGaN2i+7bI9G7/ysgVVxomRWtWvKuYHd+yMq+NDZgPtvbn9kZ4dknmL5LYvQiqatY16KSxTcKRlaOxYtxAteYI1wOot/NsEZAKdk0QSt2SOsRiQdzN1aV26qHgbmW5lFC3p0IPFn/TuG723XfZIk0NKcdNckm9d3ju5Zt8DtkQFKcJmkCqvSoSpfs=
notifications:
  slack:
    secure: XxAJNBEQCR+6Ww1UsR3lCvLtgDn/MgxaltRNuPACjzitqJc3tiPt/XGDrQB17RjOCN20D+R5htK8gzVfuqYmQVAZI+jpNF+hKtROyxXpEQAbAQbMx3EbW0kybOlUpZCsOwnuRxsrO/PCxyMkM/7xE9DJQnc83OUIr+gCIy5f5D7lBJpSkqyarWkU7TsnvCSzpC07BpXBaDspriRvmd807dNOljfTsEwjezMAL4CIBsXGOqlqEs/TDmrqt/8W0VnGH+4ThBajr4E0zMhHdtk35YaXquzC8Zq9kVoErMIQo1sh7YAfK+De+pQzznltO4gC7dK+tNqAgbbG7vW8W7f6/c93C+2Dc5/q+1CKDWq9thnvicf0puFUHX/gLxBbuhiOY2hmaYBHfwAbzQHmhtuMQxcOZxtCIGeRR+FEU/xgXhqWtzgch0pTTnaTnT24PiQjvFLoUWmhs5XnM8vOZA2qFA9WebwndLRT3+qLW1p8RxknCEWC8HZu8p0/U9QY86zdLoxrqBZBQKBgRbaRmqpgmsqOy+EyB/iqUUT2EF6EUN2eSgfw8dccq7F+uv8GGxw3VIS31oFHw8qBU6A3tzExYVmwD8tIWKUwH+ZPLOyDQob7lQbmurNV0t1DHmFV4BoL7i5YKMwIOx4qIKAcmCE0rBNT3t4kioJRJJujO9kWNo0=
